pipeline {
    agent any
    
    // agent {
    //         docker {
    //             image 'maven:3.9.4-eclipse-temurin-17'
    //             args '-v /root/.m2:/root/.m2'
    //         }
    //     }


    environment {
        COMPOSE_PROJECT_NAME = "springboot_ci_project"
    }

    stages {
        stage('Checkout Code'){
            steps {
                git url : 'https://github.com/Adarshpatel0308/Springboot_jenkins_project.git', branch: 'main'
            }
        }

        stage('Build Maven Project'){
            steps {
                sh 'RUN mvn install -Dmaven.test.skip=true'
            }
        }

        stage('Stop Previous Container'){
            steps {
                sh 'docker compose down'
            }
        }

        stage('Build Docker Image'){
            steps {
                sh 'docker build -t myspringapp:latest'
            }
        }

        stage('Run Application'){
            steps {
                sh 'docker compose up -d'
            }
        }
    }
}







